[workspace]
resolver = "2"
members = [
  "backup-shard",
  "btp",
  "ql-common",
  "ql-fsm",
  "ql-rpc",
  "ql-runtime",
  "ql-wire",
]

[workspace.package]
homepage = "https://github.com/Foundation-Devices/foundation-api"

[workspace.dependencies]
dcbor = { version = "0.23.3" }
bytes = "1"
getrandom = { version = "0.2" }
insta = { version = "1.43.2" }
rkyv = { version = "0.8" }

# workspace crates
backup-shard = { path = "backup-shard" }
btp = { path = "btp" }
ql-common = { path = "ql-common" }
ql-fsm = { path = "ql-fsm" }
ql-rpc = { path = "ql-rpc" }
ql-wire = { path = "ql-wire" }
