# SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[toolchain]
channel = "nightly-2025-06-24"
components = ["rust-analyzer", "rust-src"]
