name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Git Credentials via gh CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Configure git to use gh as a credential helper for https://github.com
          gh auth setup-git
          # Optional: Verify gh is authenticated (will show Logged in)
          gh auth status
          git config --list --show-origin

      - name: Test Git Clone Private Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Replace with a small private repo URL you have access to via the PAT
          echo "Attempting to clone a known private repository..."
          git clone https://github.com/Foundation-Devices/prime-ble-firmware.git temp_private_repo || echo "Failed to clone private repo"
          rm -rf temp_private_repo

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
