name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Git Credentials via gh CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Configure git to use gh as a credential helper for https://github.com
          gh auth setup-git

      - name: Check formatting
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: cargo fmt --all -- --check

      - name: Run Clippy (fail on warnings)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: cargo test --verbose
