[package]
name = "btp"
version = "0.1.0"
edition = "2021"
homepage.workspace = true

[dependencies]
consts = { git = "https://github.com/Foundation-Devices/prime-ble-firmware.git", features = ["dle"] }
rand = { workspace = true }
